# Type Path Mode User Group Age Argument
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/fan_speed 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/battery_limiter 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/battery_calibration 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/usb_charging 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/backlight_timeout 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/boot_animation_sound 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/*_sense/lcd_override 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/four_zoned_kb/four_zone_mode 0660 root linuwu_sense -
z /sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/four_zoned_kb/per_zone_mode 0660 root linuwu_sense -
